name: Anyway.ABC
permalink: /:title

exclude:
  [
    "CNAME",
    "node_modules",
    "README.md",
    "README2.md",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "LICENSE",
    "gulpfile.js",
  ]
